configs/loaders.js, configs/utils.js, configs/webpack.client.config.js, configs/webpack.config.js, configs/webpack.worker.config.js, src/bin/flareact.js
Adds support for a top-level `flareact.config.js` file which replaces the original `webpack.config.js`.
Users can pass custom webpack config [similar to Next.js](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config).
=> Support flareact config file

src/client/page-loader.js, src/link.js, src/router.js
This PR takes a major step toward being production-ready by implementing **prefetching** and **preloading** based on various circumstances:
- When the user hovers over a `<Link>`, the page script tag and the page props JSON are loaded
- Any `<Link>` elements within 200px of the viewport are automatically `prefetch`ed as `<link>` tags in the `<head>`.
This is mirrored from the incredible work Next.js has done to lay this foundation.
=> Prefetch and preload pages

configs/webpack.client.config.js, configs/webpack.worker.config.js, configs/webpack/plugins/build-manifest-plugin.js, package.json, src/client/page-loader.js, src/components/_document.js, src/worker/index.js, yarn.lock
- Adds a `page-manifest.json` generated by the client webpack build
- Allows the worker webpack build to load, stringify as a env var, and pass it to `_document.js`
- Document can then add scripts/styles as needed :tada:
- Also loads `_buildManfest.js` in the client, which is used in `PageLoader` to determine which dependencies need to be loaded/prefetched for a given page
THANK YOU NEXT.JS FOR ALL OF THIS!
=> Implement Page Manifest

configs/webpack.client.config.js, src/worker/worker.js
- This adds a content hash (thanks Webpack!) to static assets
- The hash changes whenever the content changes
- This means we can send back `cache-control` headers for the user's browser to cache everything for a year by default 🎉
=> Cache static assets in the browser

configs/webpack.client.config.js, src/bin/flareact.js
fixes: #24
[concurrently](https://www.npmjs.com/package/concurrently) allows `env` variables as a property in the command so no need to explicitly export them :)
=> Hopefully some easy fixes

package.json, src/client/page-loader.js, src/router.js, src/utils.js, src/worker/index.js, src/worker/pages.js, tests/router.spec.js, yarn.lock
- Exports `query` from the `router` hook object
- Includes both query string params from the URL, but also the params from dynamic page paths
- Passes `query` to `getEdgeProps` in addition to `params`
Fixes #31
=> Query enhancements

configs/webpack.client.config.js, configs/webpack/plugins/build-manifest-plugin.js, src/components/_document.js, src/worker/pages.js, tests/pages.spec.js
Where one might have the following pages:
```
/index.js
/posts/[slug].js
/posts/index.js
/docs/[slug].js
/docs.js
```
One might expect to be able to visit each of those pages as:
```
/
/posts/hello-world
/posts
/docs/doc-one
/docs
```
This PR does that.
Fixes #32
=> Fix dynamic indexes

configs/webpack.config.js, package.json, yarn.lock
Uses a noop instead.
We may need to revisit this for e.g. styled components or CSS modules.
=> Don't parse styles on the worker

docs/api-routes.md, src/worker/index.js
This is a neat convenience mechanism so you don't have to be as verbose in your API methods.
=> Automatically cast primitive data into Response objects

docs/typescript.md, examples/with-typescript/.gitignore, examples/with-typescript/README.md, examples/with-typescript/index.js, examples/with-typescript/package.json, examples/with-typescript/pages/index.tsx, examples/with-typescript/wrangler.toml
This adds docs for using TypeScript with Flareact.
It also uses a very, very simple TypeScript example.
cc #20
=> Add TypeScript example & docs

configs/webpack.client.config.js, src/bin/flareact.js
- Proxy wrangler requests through single dev server
- This allows React Fast Refresh + error catching to actually work 😍 
- Biggest change: **Dev server is at localhost:8080 now instead of 127.0.0.1:8787**. The old endpoint continues to work, however.
Future improvements:
- Unfortunately, you still see the wrangler `Listening on...` message. Hopefully the first Flareact logger will be enough to convince people to click on it
- Would be nice to be able to customize the port the dev server listens on.
=> Improve dev server

src/components/_document.js
We would like to add some script to the Head element, as we would love to execute theme change before anything starts to render. The change will allow the following script to be included in ssr response
```javascript
<Head>
<title>Hellow World</title>
<script>{`
// ...
`}
</script>
</Head>
```
https://github.com/nfl/react-helmet#server-usage
=> feat: add script tag support to flareactHead

configs/webpack.config.js
First of all, I'm so excited about this framework, it's so brilliant.
When I use the template project, I meet this warning:
```
[client] Error from chokidar (/my-project-path/node_modules/webpack/hot): Error: ENOSPC: System limit for number of file watchers reached, watch '/my-project-path/node_modules/webpack/hot/only-dev-server.js'
```
I realized maybe the webpack config miss watchOptions so all files in `node_modules` were watched.
My environment is a remote VSCode Server, so I found [this solution](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc), but this solution needs modification about `/proc/sys/` files, it's seems not good.
Then I found …
=> fix: add watchOptions.ignored for "Error: ENOSPC"

configs/webpack.client.config.js, configs/webpack/plugins/build-manifest-plugin.js
Otherwise, this file is cached in browser for one year.
=> fix: Include a build ID within _buildManifest path

src/worker/pages.js, tests/pages.spec.js
This PR is intended to address https://github.com/flareact/flareact/issues/70
The following Dynamic Page configuration will cause rendering errors because the "App" component/page will resolve to [group].js rather than _app.js
```
pages/[group].js
pages/_app.js
pages/posts/[slug].js
```
This occurs because the test for isDynamic in the resolvePagePath function will match the page path "_app.js" to the dynamic page "[group].js"
Thus the App Provider will render the component defined in [group].js as the "App" component rather than the component defined in _app.js (see https://github.com/flareact/flareact/blob/0e03f783b0fe38e827b2abc76008a42485002ebf/src/worker/render.js#L10]
To address this treat [fetching the /_app.js page](https://github.com/flareact/flareact/blob/0e03f783b0fe38e827b2abc7 …
=> bug: Dynamic Page Matches Custom App Page (_app.js) Causing Rendering Failure

src/router.js
Flareact will now scroll to the top of a page on a route change, or to a hash defined in a URL.
This was missing functionality when compared to Next.js. It also made hash-based navigation... impossible.
=> Implement scroll navigation fixes

src/router.js
fix: Ensure hash is included in new asPath during popstate
Seeing a bunch of `window.scrollTo(0, 0)` even when I'm clicking on plain hash anchors on the docs site. This is obviously a bug, and I think it has to do with `popstate` handling of new routes. 
Ugh - hope this is a good solution. There are probably a lot of leaks in the router.
=> Fix hash routing weirdness

src/worker/index.js, src/worker/pages.js
**What does this PR do?**
It passes the `event` supplied to `handleCachedPageRequest` to the `getPageProps` method, allowing us to access `event` in the `getEdgeProps` method.
The example use case is described in #82. I also realised that the implementation itself is not new as this has been implemented in @cj's PR in #61 so this just pulls this feature out into its own smaller PR.
=> feat: add event argument to getPageProps

docs/built-in-css-support.md
I'm loving this project, thanks for the hardwork bootstrapping this! I have a Nextjs application that I'm looking to port over to flareact to take advantage of some cloudflare worker features.
Looking through the docs, I noticed that the css module example had a class name mismatch between the css file and the react component. This is not a big fix, but hopefully this can help avoid some confusion if someone is trying to follow the docs to get started with css modules.
=> Fix css modules example to have correct class name

src/worker/pages.js, tests/pages.spec.js
Allows any characters other than `/` in dynamic pages. Any other potentially "breaking" characters should be url encoded by the user and not part of flareact.
=> fix: unicode in dynamic pages

docs/index.md
`master` branch has been renamed to `main`
=> docs: fix broken link

docs/manifest.json, docs/react-native.md
I was able to integrate Flareact with React Native and React Native Web, and actually run the app both in the browser and on my mobile phone. These are preliminary instructions following the steps I took. I marked it as experimental because I haven't done extensive testing beyond a simple boilerplate app, but I will keep this updated as I move along. So far it's looking pretty good.
=> Add instructions for integrating with React Native

docs/custom-404-error-page.md, docs/manifest.json, docs/static-file-serving.md
As discussed in https://github.com/flareact/flareact/discussions/130 it is currently not possible to add a custom 404 Not Found page in `/pages/404.js`, [like with Next.js](https://nextjs.org/docs/advanced-features/custom-error-page#404-page).
It _is_ however, possible to add a static `/public/404.html` that is rendered as the 404 Not Found error document. This follows the convention from many static hosting platforms, e.g. [GitHub pages](https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site), and is documented in the [Cloudflare worker sites template](https://github.com/cloudflare/worker-sites-template/blob/master/public/404.html).
This behavior is implemented in `worker.js`: …
=> Document custom 404 Not Found page

docs/getting-started.md
I'm a wrangler noob and kept receiving this error when trying to run `npm run dev` in a new Flareact project:
```
[HPM] Error occurred while trying to proxy request / from localhost:8080 to http://localhost:8787 (ECONNREFUSED)
```
I couldn't figure out why port 8787 wasn't connecting.  Turns out I was missing the cargo-generate.toml file + contents.  Added this and Flareact started working straight away.
Hopefully this will help somebody in the future with the same issue as me.
=> Add cargo-generate.toml to Manual Installation steps

src/worker/pages.js
When a page like /path/index.js is hard loaded the returned page path is /path/index. When attempting to load /path/index on the client side, the promise is never resolved and so the page is never hydrated. Have trimmed the /index from the end of the page path to match the router returned page path which does allow hydration to happen.
=> fixed hydration of path/index files
